name: run-tests
on:
  pull_request:
    branches: gtest-KKiiim
  push:
    branches: gtest-KKiiim

jobs:
  gtest_qsort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install gcc make cmake
        run: 
         sudo apt-get update -y -qq && sudo apt-get install gcc g++ libgtest-dev cmake make build-essential sed -y --no-install-recommends

      - name: install gcc-aarch64-linux-gnu and qemu-user
        run: 
          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu && sudo apt install qemu-user

      - name: build gtest-arm
        run:
          mkdir ~/gtest && cd ~/gtest && git clone https://github.com/google/googletest.git && mkdir ~/gtest/gtest-build && cd gtest-build/ && cmake ../googletest/ -DCMAKE_INSTALL_PREFIX=./_install && make && make install && mkdir ~/gtest/gtest-build-arm && cd ~/gtest/gtest-build-arm && cmake ../googletest -DMAKE_INSTALL_PREFIX=./_install -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ && sudo make && sudo make install
      
      - name: cmake make and run
        run: 
          cd ctest-cmake-qsort && mkdir build && cd build && cmake .. && make && ctest
