name: run-tests
on:
  pull_request:
    branches: gtest-KKiiim
  push:
    branches: gtest-KKiiim

jobs:
  gtest_qsort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install gcc gTest
        run: 
         sudo apt-get update -y -qq && sudo apt-get install gcc g++ libgtest-dev cmake make  build-essential sed -y --no-install-recommends

      - name: install gcc-aarch64-linux-gnu and qemu-user
        run: sudo apt-get install gcc-aarch64-linux-gnu && sudo apt install qemu-user
        
      
      - name: complie and run
        run: cd qsort/final-qsort && aarch64-linux-gnu-gcc asmQsort.s qsort.c -o outfile.bin && qemu-aarch64 -L /usr/aarch64-linux-gnu ./outfile.bin
