name: wasm-tests
on:
  pull_request:
    branches: gtest-KKiiim
  push:
    branches: gtest-KKiiim

jobs:
  wasm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install mocha and run sum_n mocha-test
        run: 
          cd wasm-practice/sum-n && npm install -g mocha && npm install --save-dev mocha && npx mocha sum_n.test.js
